package com.carebridge.entity;

/**
 * Types of notifications generated by the CareBridge system.
 */
public enum NotificationType {
    APPOINTMENT_REQUEST,
    APPOINTMENT_ACCEPTED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_COMPLETED,
    APPOINTMENT_REMINDER,
    SYSTEM
}
